task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 512
  crop: 512
  data_layout: NCHW
  reverse_channels: true
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 0.017125
  - 0.017507
  - 0.017429
  runtime_options:
    advanced_options:quantization_scale_type: 4
    tensor_bits: 8
    accuracy_level: 0
    advanced_options:high_resolution_optimization: 1
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 10
    advanced_options:calibration_iterations: 1
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
  model_path: regnet_x_800mf_tv_512x512.onnx
  model_id: cl-6131
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_top1%: null
  model_shortlist: 200
  compact_name: regNetX-800mf-pycls-512x512
  shortlisted: false
